version: 2.1
executors:
  publisher:
    environment:
      IMAGE_NAME: cloudokihub/appdoki-be
    docker:
      - image: cimg/base:2020.01

jobs:
  test:
    docker:
      - image: cimg/go:1.16
    steps:
      - checkout
      - run: go test ./app/... -v

  build:
    executor: publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME .
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker push $IMAGE_NAME

  deploy:
    machine: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "cf:04:e1:6b:66:0c:8f:80:a9:b9:77:21:12:15:aa:d9"
      - run:
          name: Deploy Over SSH
          command: |
            scp -r -o StrictHostKeyChecking=no docker-compose.yml Makefile $SSH_USER@$SSH_HOST:~/appdoki/
            ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "cd appdoki && docker-compose pull && docker-compose up -d"

workflows:
  version: 2
  build_deploy:
    jobs:
      - test
      - build:
          context: cloudoki-docker
          filters:
            branches:
              only:
                - main
          requires:
            - test
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - build